### ISSUE TITLE
Attempting to store the same event more than once result in response code 503

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#591]
### Description of the bug

We need to look into why the response code for the new duplicate check is 503 and then change it to be 400 instead.

Npgsql.PostgresException: 23505: duplicate key value violates unique constraint "idx_events_id_source"

### Steps To Reproduce

Attempt to have the same event registered twice.

```[tasklist]
### Dependencies
- [ ] https://github.com/Altinn/team-core-private/issues/66
```

**Comment by hansdragnes** [comment]
Look into: threshold, frequency (SLO)

**Comment by olebhansen** [comment]
FYI; @SandGrainOne made a manual override in the "prod-platform-events_5xx" rule to ignore 503 for alerting. This is temporary as a Terraform re-provisioning will re-enable the rule.

the intent is to prevent night-time alarms (calling/waking the on-call person) for an unactionable/expected situation.

When this issue has been resolved, the 503 should be re-introduced.

**Comment by HenningNormann** [comment]
@olebhansen @SandGrainOne This is just a temporary problem because the index is deploy manually to prod, but the updated stored procedure is not yet deployed. When the procedure is updated, the duplicate situation will be ignored.

I hotfixed the index to avoid problems with slow response during deployment. I assumed that there would be almost 0 errors between hotfix time and normal production time because we haven't seen duplicates for a long time.

**Comment by olebhansen** [comment]
Blocked/pending next prod-deploy. The remaining work is to re-enable the 503 erorrs in the alarm, after the next deploy (week 40).

**Comment by SandGrainOne** [comment]
The changes are already in production.

**Comment by SandGrainOne** [comment]
The alert rule has been updated to include a check for 503 errors again
